/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.example

import org.mongodb.scala.{Document, MongoClient, MongoCollection, MongoDatabase}

object App {
  def main(args: Array[String]): Unit = {

    val client: MongoClient = MongoClient()
    val database: MongoDatabase = client.getDatabase("latest_db")
    val collection: MongoCollection[Document] = database.getCollection("students")

    // insert a document
    val document: Document = Document("name" -> "John", "age" -> 51)
    val insertObservable = collection.insertOne(document)
    println("Document inserted")

    // find documents
    collection.find()
      .collect()
      .subscribe((results: Seq[Document]) => println(s"Found: #${results.size}"))
  }

}
